ingress:
  enabled: true
  name: test-ingress
  host: test-myvanish-url

nginx:
  enabled: true
  name: nginx
  type: NodePort
  port: 80
  targetPort: 80
  namespace: namepsace-1
  image: nginx:1.14.2
  replicas: 2

configmap:
  enabled: true
  name: varnish-config

varnish:
  enabled: true
  name: varnish
  image: varnish:7.1.0
  vclconfig: /etc/varnish/default.vcl
  containerport: 80

vclTemplate: |
  vcl 4.0;

  import std;
  import directors;

  // ".Frontends" is a slice that contains all known Varnish instances
  // (as selected by the service specified by -frontend-service).
  // The backend name needs to be the Pod name, since this value is compared
  // to the server identity ("server.identity" [1]) later.
  //
  //   [1]: https://varnish-cache.org/docs/6.4/reference/vcl.html#local-server-remote-and-client
  
  backend default {
      .host = "nginx-service";
      .port = "80";
  }
  


  sub vcl_recv
  {
      set req.backend_hint = default;

  }


  